use crate::{
    system::{
        spu::{
            constants::*,
            types::*,
        },
        types::State,
    },
    types::memory::*,
};

pub fn get_transfer_mode(control: &B16Register) -> TransferMode {
    match control.read_bitfield(CONTROL_TRANSFER_MODE) {
        0 => TransferMode::Stop,
        1 => TransferMode::ManualWrite,
        2 => TransferMode::DmaWrite,
        3 => TransferMode::DmaRead,
        _ => unreachable!("Invalid transfer mode"),
    }
}

pub fn get_voll(state: &State, voice_id: usize) -> &B16Register {
    match voice_id {
        0 => &state.spu.voice0_vollr,
        1 => &state.spu.voice1_vollr,
        2 => &state.spu.voice2_vollr,
        3 => &state.spu.voice3_vollr,
        4 => &state.spu.voice4_vollr,
        5 => &state.spu.voice5_vollr,
        6 => &state.spu.voice6_vollr,
        7 => &state.spu.voice7_vollr,
        8 => &state.spu.voice8_vollr,
        9 => &state.spu.voice9_vollr,
        10 => &state.spu.voice10_vollr,
        11 => &state.spu.voice11_vollr,
        12 => &state.spu.voice12_vollr,
        13 => &state.spu.voice13_vollr,
        14 => &state.spu.voice14_vollr,
        15 => &state.spu.voice15_vollr,
        16 => &state.spu.voice16_vollr,
        17 => &state.spu.voice17_vollr,
        18 => &state.spu.voice18_vollr,
        19 => &state.spu.voice19_vollr,
        20 => &state.spu.voice20_vollr,
        21 => &state.spu.voice21_vollr,
        22 => &state.spu.voice22_vollr,
        23 => &state.spu.voice23_vollr,
        _ => unreachable!("Invalid voice id"),
    }
}

pub fn get_volr(state: &State, voice_id: usize) -> &B16Register {
    match voice_id {
        0 => &state.spu.voice0_volrr,
        1 => &state.spu.voice1_volrr,
        2 => &state.spu.voice2_volrr,
        3 => &state.spu.voice3_volrr,
        4 => &state.spu.voice4_volrr,
        5 => &state.spu.voice5_volrr,
        6 => &state.spu.voice6_volrr,
        7 => &state.spu.voice7_volrr,
        8 => &state.spu.voice8_volrr,
        9 => &state.spu.voice9_volrr,
        10 => &state.spu.voice10_volrr,
        11 => &state.spu.voice11_volrr,
        12 => &state.spu.voice12_volrr,
        13 => &state.spu.voice13_volrr,
        14 => &state.spu.voice14_volrr,
        15 => &state.spu.voice15_volrr,
        16 => &state.spu.voice16_volrr,
        17 => &state.spu.voice17_volrr,
        18 => &state.spu.voice18_volrr,
        19 => &state.spu.voice19_volrr,
        20 => &state.spu.voice20_volrr,
        21 => &state.spu.voice21_volrr,
        22 => &state.spu.voice22_volrr,
        23 => &state.spu.voice23_volrr,
        _ => unreachable!("Invalid voice id"),
    }
}

pub fn get_srate(state: &State, voice_id: usize) -> &B16Register {
    match voice_id {
        0 => &state.spu.voice0_srate,
        1 => &state.spu.voice1_srate,
        2 => &state.spu.voice2_srate,
        3 => &state.spu.voice3_srate,
        4 => &state.spu.voice4_srate,
        5 => &state.spu.voice5_srate,
        6 => &state.spu.voice6_srate,
        7 => &state.spu.voice7_srate,
        8 => &state.spu.voice8_srate,
        9 => &state.spu.voice9_srate,
        10 => &state.spu.voice10_srate,
        11 => &state.spu.voice11_srate,
        12 => &state.spu.voice12_srate,
        13 => &state.spu.voice13_srate,
        14 => &state.spu.voice14_srate,
        15 => &state.spu.voice15_srate,
        16 => &state.spu.voice16_srate,
        17 => &state.spu.voice17_srate,
        18 => &state.spu.voice18_srate,
        19 => &state.spu.voice19_srate,
        20 => &state.spu.voice20_srate,
        21 => &state.spu.voice21_srate,
        22 => &state.spu.voice22_srate,
        23 => &state.spu.voice23_srate,
        _ => unreachable!("Invalid voice id"),
    }
}

pub fn get_saddr(state: &State, voice_id: usize) -> &B16Register {
    match voice_id {
        0 => &state.spu.voice0_saddr,
        1 => &state.spu.voice1_saddr,
        2 => &state.spu.voice2_saddr,
        3 => &state.spu.voice3_saddr,
        4 => &state.spu.voice4_saddr,
        5 => &state.spu.voice5_saddr,
        6 => &state.spu.voice6_saddr,
        7 => &state.spu.voice7_saddr,
        8 => &state.spu.voice8_saddr,
        9 => &state.spu.voice9_saddr,
        10 => &state.spu.voice10_saddr,
        11 => &state.spu.voice11_saddr,
        12 => &state.spu.voice12_saddr,
        13 => &state.spu.voice13_saddr,
        14 => &state.spu.voice14_saddr,
        15 => &state.spu.voice15_saddr,
        16 => &state.spu.voice16_saddr,
        17 => &state.spu.voice17_saddr,
        18 => &state.spu.voice18_saddr,
        19 => &state.spu.voice19_saddr,
        20 => &state.spu.voice20_saddr,
        21 => &state.spu.voice21_saddr,
        22 => &state.spu.voice22_saddr,
        23 => &state.spu.voice23_saddr,
        _ => unreachable!("Invalid voice id"),
    }
}

pub fn get_adsr(state: &State, voice_id: usize) -> &B32Register {
    match voice_id {
        0 => &state.spu.voice0_adsr,
        1 => &state.spu.voice1_adsr,
        2 => &state.spu.voice2_adsr,
        3 => &state.spu.voice3_adsr,
        4 => &state.spu.voice4_adsr,
        5 => &state.spu.voice5_adsr,
        6 => &state.spu.voice6_adsr,
        7 => &state.spu.voice7_adsr,
        8 => &state.spu.voice8_adsr,
        9 => &state.spu.voice9_adsr,
        10 => &state.spu.voice10_adsr,
        11 => &state.spu.voice11_adsr,
        12 => &state.spu.voice12_adsr,
        13 => &state.spu.voice13_adsr,
        14 => &state.spu.voice14_adsr,
        15 => &state.spu.voice15_adsr,
        16 => &state.spu.voice16_adsr,
        17 => &state.spu.voice17_adsr,
        18 => &state.spu.voice18_adsr,
        19 => &state.spu.voice19_adsr,
        20 => &state.spu.voice20_adsr,
        21 => &state.spu.voice21_adsr,
        22 => &state.spu.voice22_adsr,
        23 => &state.spu.voice23_adsr,
        _ => unreachable!("Invalid voice id"),
    }
}

pub fn get_cvol(state: &State, voice_id: usize) -> &B16Register {
    match voice_id {
        0 => &state.spu.voice0_cvol,
        1 => &state.spu.voice1_cvol,
        2 => &state.spu.voice2_cvol,
        3 => &state.spu.voice3_cvol,
        4 => &state.spu.voice4_cvol,
        5 => &state.spu.voice5_cvol,
        6 => &state.spu.voice6_cvol,
        7 => &state.spu.voice7_cvol,
        8 => &state.spu.voice8_cvol,
        9 => &state.spu.voice9_cvol,
        10 => &state.spu.voice10_cvol,
        11 => &state.spu.voice11_cvol,
        12 => &state.spu.voice12_cvol,
        13 => &state.spu.voice13_cvol,
        14 => &state.spu.voice14_cvol,
        15 => &state.spu.voice15_cvol,
        16 => &state.spu.voice16_cvol,
        17 => &state.spu.voice17_cvol,
        18 => &state.spu.voice18_cvol,
        19 => &state.spu.voice19_cvol,
        20 => &state.spu.voice20_cvol,
        21 => &state.spu.voice21_cvol,
        22 => &state.spu.voice22_cvol,
        23 => &state.spu.voice23_cvol,
        _ => unreachable!("Invalid voice id"),
    }
}

pub fn get_raddr(state: &State, voice_id: usize) -> &B16Register {
    match voice_id {
        0 => &state.spu.voice0_raddr,
        1 => &state.spu.voice1_raddr,
        2 => &state.spu.voice2_raddr,
        3 => &state.spu.voice3_raddr,
        4 => &state.spu.voice4_raddr,
        5 => &state.spu.voice5_raddr,
        6 => &state.spu.voice6_raddr,
        7 => &state.spu.voice7_raddr,
        8 => &state.spu.voice8_raddr,
        9 => &state.spu.voice9_raddr,
        10 => &state.spu.voice10_raddr,
        11 => &state.spu.voice11_raddr,
        12 => &state.spu.voice12_raddr,
        13 => &state.spu.voice13_raddr,
        14 => &state.spu.voice14_raddr,
        15 => &state.spu.voice15_raddr,
        16 => &state.spu.voice16_raddr,
        17 => &state.spu.voice17_raddr,
        18 => &state.spu.voice18_raddr,
        19 => &state.spu.voice19_raddr,
        20 => &state.spu.voice20_raddr,
        21 => &state.spu.voice21_raddr,
        22 => &state.spu.voice22_raddr,
        23 => &state.spu.voice23_raddr,
        _ => unreachable!("Invalid voice id"),
    }
}

pub fn get_play_state(state: &mut ControllerState, voice_id: usize) -> &mut PlayState {
    match voice_id {
        0 => &mut state.spu.dac.voice0_state as *mut PlayState,
        1 => &mut state.spu.dac.voice1_state as *mut PlayState,
        2 => &mut state.spu.dac.voice2_state as *mut PlayState,
        3 => &mut state.spu.dac.voice3_state as *mut PlayState,
        4 => &mut state.spu.dac.voice4_state as *mut PlayState,
        5 => &mut state.spu.dac.voice5_state as *mut PlayState,
        6 => &mut state.spu.dac.voice6_state as *mut PlayState,
        7 => &mut state.spu.dac.voice7_state as *mut PlayState,
        8 => &mut state.spu.dac.voice8_state as *mut PlayState,
        9 => &mut state.spu.dac.voice9_state as *mut PlayState,
        10 => &mut state.spu.dac.voice10_state as *mut PlayState,
        11 => &mut state.spu.dac.voice11_state as *mut PlayState,
        12 => &mut state.spu.dac.voice12_state as *mut PlayState,
        13 => &mut state.spu.dac.voice13_state as *mut PlayState,
        14 => &mut state.spu.dac.voice14_state as *mut PlayState,
        15 => &mut state.spu.dac.voice15_state as *mut PlayState,
        16 => &mut state.spu.dac.voice16_state as *mut PlayState,
        17 => &mut state.spu.dac.voice17_state as *mut PlayState,
        18 => &mut state.spu.dac.voice18_state as *mut PlayState,
        19 => &mut state.spu.dac.voice19_state as *mut PlayState,
        20 => &mut state.spu.dac.voice20_state as *mut PlayState,
        21 => &mut state.spu.dac.voice21_state as *mut PlayState,
        22 => &mut state.spu.dac.voice22_state as *mut PlayState,
        23 => &mut state.spu.dac.voice23_state as *mut PlayState,
        _ => unreachable!("Invalid voice id"),
    }
}
