mod dac;
mod transfer;

use crate::types::{
    fifo::{
        debug::DebugState,
        Fifo,
    },
    memory::*,
};
pub use dac::*;
use parking_lot::Mutex;
pub use transfer::*;

pub struct ControllerState {
    pub enabled: bool,
    pub muted: bool,
    pub transfer_state: TransferState,
    pub dac_state: DacState,
    pub memory: Vec<u8>,
}

impl ControllerState {
    pub fn new() -> ControllerState {
        ControllerState {
            enabled: false,
            muted: false,
            transfer_state: TransferState::new(),
            dac_state: DacState::new(),
            memory: vec![0; 0x8_0000],
        }
    }
}

pub struct State {
    pub main_volume_left: B16LevelRegister,
    pub main_volume_right: B16LevelRegister,
    pub reverb_volume: B32LevelRegister,

    pub voice_key_on: B32EdgeRegister,
    pub voice_key_off: B32EdgeRegister,
    pub voice_channel_fm: B32LevelRegister,
    pub voice_channel_noise: B32LevelRegister,
    pub voice_channel_reverb: B32LevelRegister,
    pub voice_channel_status: B32LevelRegister,

    pub unknown_0: B16LevelRegister,
    pub reverb_start_address: B16LevelRegister,
    pub irq_address: B16LevelRegister,
    pub control: B16EdgeRegister,
    pub data_transfer_address: B16EdgeRegister,
    pub data_fifo: Fifo<u16>,
    pub data_transfer_control: B16LevelRegister,
    pub stat: B16LevelRegister,
    pub cd_volume: B32LevelRegister,
    pub extern_volume: B32LevelRegister,
    pub current_volume_left: B16LevelRegister,
    pub current_volume_right: B16LevelRegister,
    pub unknown_1: B32LevelRegister,

    pub controller_state: Mutex<ControllerState>,

    pub dapf1: B16LevelRegister,
    pub dapf2: B16LevelRegister,
    pub viir: B16LevelRegister,
    pub vcomb1: B16LevelRegister,
    pub vcomb2: B16LevelRegister,
    pub vcomb3: B16LevelRegister,
    pub vcomb4: B16LevelRegister,
    pub vwall: B16LevelRegister,
    pub vapf1: B16LevelRegister,
    pub vapf2: B16LevelRegister,
    pub msame: B32LevelRegister,
    pub mcomb1: B32LevelRegister,
    pub mcomb2: B32LevelRegister,
    pub dsame: B32LevelRegister,
    pub mdiff: B32LevelRegister,
    pub mcomb3: B32LevelRegister,
    pub mcomb4: B32LevelRegister,
    pub ddiff: B32LevelRegister,
    pub mapf1: B32LevelRegister,
    pub mapf2: B32LevelRegister,
    pub vin: B32LevelRegister,

    pub voice0_voll: B16LevelRegister,
    pub voice0_volr: B16LevelRegister,
    pub voice0_srate: B16LevelRegister,
    pub voice0_saddr: B16LevelRegister,
    pub voice0_adsr: B32LevelRegister,
    pub voice0_cvol: B16LevelRegister,
    pub voice0_raddr: B16LevelRegister,

    pub voice1_voll: B16LevelRegister,
    pub voice1_volr: B16LevelRegister,
    pub voice1_srate: B16LevelRegister,
    pub voice1_saddr: B16LevelRegister,
    pub voice1_adsr: B32LevelRegister,
    pub voice1_cvol: B16LevelRegister,
    pub voice1_raddr: B16LevelRegister,

    pub voice2_voll: B16LevelRegister,
    pub voice2_volr: B16LevelRegister,
    pub voice2_srate: B16LevelRegister,
    pub voice2_saddr: B16LevelRegister,
    pub voice2_adsr: B32LevelRegister,
    pub voice2_cvol: B16LevelRegister,
    pub voice2_raddr: B16LevelRegister,

    pub voice3_voll: B16LevelRegister,
    pub voice3_volr: B16LevelRegister,
    pub voice3_srate: B16LevelRegister,
    pub voice3_saddr: B16LevelRegister,
    pub voice3_adsr: B32LevelRegister,
    pub voice3_cvol: B16LevelRegister,
    pub voice3_raddr: B16LevelRegister,

    pub voice4_voll: B16LevelRegister,
    pub voice4_volr: B16LevelRegister,
    pub voice4_srate: B16LevelRegister,
    pub voice4_saddr: B16LevelRegister,
    pub voice4_adsr: B32LevelRegister,
    pub voice4_cvol: B16LevelRegister,
    pub voice4_raddr: B16LevelRegister,

    pub voice5_voll: B16LevelRegister,
    pub voice5_volr: B16LevelRegister,
    pub voice5_srate: B16LevelRegister,
    pub voice5_saddr: B16LevelRegister,
    pub voice5_adsr: B32LevelRegister,
    pub voice5_cvol: B16LevelRegister,
    pub voice5_raddr: B16LevelRegister,

    pub voice6_voll: B16LevelRegister,
    pub voice6_volr: B16LevelRegister,
    pub voice6_srate: B16LevelRegister,
    pub voice6_saddr: B16LevelRegister,
    pub voice6_adsr: B32LevelRegister,
    pub voice6_cvol: B16LevelRegister,
    pub voice6_raddr: B16LevelRegister,

    pub voice7_voll: B16LevelRegister,
    pub voice7_volr: B16LevelRegister,
    pub voice7_srate: B16LevelRegister,
    pub voice7_saddr: B16LevelRegister,
    pub voice7_adsr: B32LevelRegister,
    pub voice7_cvol: B16LevelRegister,
    pub voice7_raddr: B16LevelRegister,

    pub voice8_voll: B16LevelRegister,
    pub voice8_volr: B16LevelRegister,
    pub voice8_srate: B16LevelRegister,
    pub voice8_saddr: B16LevelRegister,
    pub voice8_adsr: B32LevelRegister,
    pub voice8_cvol: B16LevelRegister,
    pub voice8_raddr: B16LevelRegister,

    pub voice9_voll: B16LevelRegister,
    pub voice9_volr: B16LevelRegister,
    pub voice9_srate: B16LevelRegister,
    pub voice9_saddr: B16LevelRegister,
    pub voice9_adsr: B32LevelRegister,
    pub voice9_cvol: B16LevelRegister,
    pub voice9_raddr: B16LevelRegister,

    pub voice10_voll: B16LevelRegister,
    pub voice10_volr: B16LevelRegister,
    pub voice10_srate: B16LevelRegister,
    pub voice10_saddr: B16LevelRegister,
    pub voice10_adsr: B32LevelRegister,
    pub voice10_cvol: B16LevelRegister,
    pub voice10_raddr: B16LevelRegister,

    pub voice11_voll: B16LevelRegister,
    pub voice11_volr: B16LevelRegister,
    pub voice11_srate: B16LevelRegister,
    pub voice11_saddr: B16LevelRegister,
    pub voice11_adsr: B32LevelRegister,
    pub voice11_cvol: B16LevelRegister,
    pub voice11_raddr: B16LevelRegister,

    pub voice12_voll: B16LevelRegister,
    pub voice12_volr: B16LevelRegister,
    pub voice12_srate: B16LevelRegister,
    pub voice12_saddr: B16LevelRegister,
    pub voice12_adsr: B32LevelRegister,
    pub voice12_cvol: B16LevelRegister,
    pub voice12_raddr: B16LevelRegister,

    pub voice13_voll: B16LevelRegister,
    pub voice13_volr: B16LevelRegister,
    pub voice13_srate: B16LevelRegister,
    pub voice13_saddr: B16LevelRegister,
    pub voice13_adsr: B32LevelRegister,
    pub voice13_cvol: B16LevelRegister,
    pub voice13_raddr: B16LevelRegister,

    pub voice14_voll: B16LevelRegister,
    pub voice14_volr: B16LevelRegister,
    pub voice14_srate: B16LevelRegister,
    pub voice14_saddr: B16LevelRegister,
    pub voice14_adsr: B32LevelRegister,
    pub voice14_cvol: B16LevelRegister,
    pub voice14_raddr: B16LevelRegister,

    pub voice15_voll: B16LevelRegister,
    pub voice15_volr: B16LevelRegister,
    pub voice15_srate: B16LevelRegister,
    pub voice15_saddr: B16LevelRegister,
    pub voice15_adsr: B32LevelRegister,
    pub voice15_cvol: B16LevelRegister,
    pub voice15_raddr: B16LevelRegister,

    pub voice16_voll: B16LevelRegister,
    pub voice16_volr: B16LevelRegister,
    pub voice16_srate: B16LevelRegister,
    pub voice16_saddr: B16LevelRegister,
    pub voice16_adsr: B32LevelRegister,
    pub voice16_cvol: B16LevelRegister,
    pub voice16_raddr: B16LevelRegister,

    pub voice17_voll: B16LevelRegister,
    pub voice17_volr: B16LevelRegister,
    pub voice17_srate: B16LevelRegister,
    pub voice17_saddr: B16LevelRegister,
    pub voice17_adsr: B32LevelRegister,
    pub voice17_cvol: B16LevelRegister,
    pub voice17_raddr: B16LevelRegister,

    pub voice18_voll: B16LevelRegister,
    pub voice18_volr: B16LevelRegister,
    pub voice18_srate: B16LevelRegister,
    pub voice18_saddr: B16LevelRegister,
    pub voice18_adsr: B32LevelRegister,
    pub voice18_cvol: B16LevelRegister,
    pub voice18_raddr: B16LevelRegister,

    pub voice19_voll: B16LevelRegister,
    pub voice19_volr: B16LevelRegister,
    pub voice19_srate: B16LevelRegister,
    pub voice19_saddr: B16LevelRegister,
    pub voice19_adsr: B32LevelRegister,
    pub voice19_cvol: B16LevelRegister,
    pub voice19_raddr: B16LevelRegister,

    pub voice20_voll: B16LevelRegister,
    pub voice20_volr: B16LevelRegister,
    pub voice20_srate: B16LevelRegister,
    pub voice20_saddr: B16LevelRegister,
    pub voice20_adsr: B32LevelRegister,
    pub voice20_cvol: B16LevelRegister,
    pub voice20_raddr: B16LevelRegister,

    pub voice21_voll: B16LevelRegister,
    pub voice21_volr: B16LevelRegister,
    pub voice21_srate: B16LevelRegister,
    pub voice21_saddr: B16LevelRegister,
    pub voice21_adsr: B32LevelRegister,
    pub voice21_cvol: B16LevelRegister,
    pub voice21_raddr: B16LevelRegister,

    pub voice22_voll: B16LevelRegister,
    pub voice22_volr: B16LevelRegister,
    pub voice22_srate: B16LevelRegister,
    pub voice22_saddr: B16LevelRegister,
    pub voice22_adsr: B32LevelRegister,
    pub voice22_cvol: B16LevelRegister,
    pub voice22_raddr: B16LevelRegister,

    pub voice23_voll: B16LevelRegister,
    pub voice23_volr: B16LevelRegister,
    pub voice23_srate: B16LevelRegister,
    pub voice23_saddr: B16LevelRegister,
    pub voice23_adsr: B32LevelRegister,
    pub voice23_cvol: B16LevelRegister,
    pub voice23_raddr: B16LevelRegister,
}

impl State {
    pub fn new() -> State {
        State {
            main_volume_left: B16LevelRegister::new(),
            main_volume_right: B16LevelRegister::new(),
            reverb_volume: B32LevelRegister::new(),
            voice_key_on: B32EdgeRegister::new(),
            voice_key_off: B32EdgeRegister::new(),
            voice_channel_fm: B32LevelRegister::new(),
            voice_channel_noise: B32LevelRegister::new(),
            voice_channel_reverb: B32LevelRegister::new(),
            voice_channel_status: B32LevelRegister::new(),
            unknown_0: B16LevelRegister::new(),
            reverb_start_address: B16LevelRegister::new(),
            irq_address: B16LevelRegister::new(),
            data_transfer_address: B16EdgeRegister::new(),
            control: B16EdgeRegister::new(),
            data_transfer_control: B16LevelRegister::new(),
            stat: B16LevelRegister::new(),
            cd_volume: B32LevelRegister::new(),
            extern_volume: B32LevelRegister::new(),
            current_volume_left: B16LevelRegister::new(),
            current_volume_right: B16LevelRegister::new(),
            unknown_1: B32LevelRegister::new(),
            dapf1: B16LevelRegister::new(),
            dapf2: B16LevelRegister::new(),
            viir: B16LevelRegister::new(),
            vcomb1: B16LevelRegister::new(),
            vcomb2: B16LevelRegister::new(),
            vcomb3: B16LevelRegister::new(),
            vcomb4: B16LevelRegister::new(),
            vwall: B16LevelRegister::new(),
            vapf1: B16LevelRegister::new(),
            vapf2: B16LevelRegister::new(),
            msame: B32LevelRegister::new(),
            mcomb1: B32LevelRegister::new(),
            mcomb2: B32LevelRegister::new(),
            dsame: B32LevelRegister::new(),
            mdiff: B32LevelRegister::new(),
            mcomb3: B32LevelRegister::new(),
            mcomb4: B32LevelRegister::new(),
            ddiff: B32LevelRegister::new(),
            mapf1: B32LevelRegister::new(),
            mapf2: B32LevelRegister::new(),
            vin: B32LevelRegister::new(),
            voice0_voll: B16LevelRegister::new(),
            voice0_volr: B16LevelRegister::new(),
            voice0_srate: B16LevelRegister::new(),
            voice0_saddr: B16LevelRegister::new(),
            voice0_adsr: B32LevelRegister::new(),
            voice0_cvol: B16LevelRegister::new(),
            voice0_raddr: B16LevelRegister::new(),
            voice1_voll: B16LevelRegister::new(),
            voice1_volr: B16LevelRegister::new(),
            voice1_srate: B16LevelRegister::new(),
            voice1_saddr: B16LevelRegister::new(),
            voice1_adsr: B32LevelRegister::new(),
            voice1_cvol: B16LevelRegister::new(),
            voice1_raddr: B16LevelRegister::new(),
            voice2_voll: B16LevelRegister::new(),
            voice2_volr: B16LevelRegister::new(),
            voice2_srate: B16LevelRegister::new(),
            voice2_saddr: B16LevelRegister::new(),
            voice2_adsr: B32LevelRegister::new(),
            voice2_cvol: B16LevelRegister::new(),
            voice2_raddr: B16LevelRegister::new(),
            voice3_voll: B16LevelRegister::new(),
            voice3_volr: B16LevelRegister::new(),
            voice3_srate: B16LevelRegister::new(),
            voice3_saddr: B16LevelRegister::new(),
            voice3_adsr: B32LevelRegister::new(),
            voice3_cvol: B16LevelRegister::new(),
            voice3_raddr: B16LevelRegister::new(),
            voice4_voll: B16LevelRegister::new(),
            voice4_volr: B16LevelRegister::new(),
            voice4_srate: B16LevelRegister::new(),
            voice4_saddr: B16LevelRegister::new(),
            voice4_adsr: B32LevelRegister::new(),
            voice4_cvol: B16LevelRegister::new(),
            voice4_raddr: B16LevelRegister::new(),
            voice5_voll: B16LevelRegister::new(),
            voice5_volr: B16LevelRegister::new(),
            voice5_srate: B16LevelRegister::new(),
            voice5_saddr: B16LevelRegister::new(),
            voice5_adsr: B32LevelRegister::new(),
            voice5_cvol: B16LevelRegister::new(),
            voice5_raddr: B16LevelRegister::new(),
            voice6_voll: B16LevelRegister::new(),
            voice6_volr: B16LevelRegister::new(),
            voice6_srate: B16LevelRegister::new(),
            voice6_saddr: B16LevelRegister::new(),
            voice6_adsr: B32LevelRegister::new(),
            voice6_cvol: B16LevelRegister::new(),
            voice6_raddr: B16LevelRegister::new(),
            voice7_voll: B16LevelRegister::new(),
            voice7_volr: B16LevelRegister::new(),
            voice7_srate: B16LevelRegister::new(),
            voice7_saddr: B16LevelRegister::new(),
            voice7_adsr: B32LevelRegister::new(),
            voice7_cvol: B16LevelRegister::new(),
            voice7_raddr: B16LevelRegister::new(),
            voice8_voll: B16LevelRegister::new(),
            voice8_volr: B16LevelRegister::new(),
            voice8_srate: B16LevelRegister::new(),
            voice8_saddr: B16LevelRegister::new(),
            voice8_adsr: B32LevelRegister::new(),
            voice8_cvol: B16LevelRegister::new(),
            voice8_raddr: B16LevelRegister::new(),
            voice9_voll: B16LevelRegister::new(),
            voice9_volr: B16LevelRegister::new(),
            voice9_srate: B16LevelRegister::new(),
            voice9_saddr: B16LevelRegister::new(),
            voice9_adsr: B32LevelRegister::new(),
            voice9_cvol: B16LevelRegister::new(),
            voice9_raddr: B16LevelRegister::new(),
            voice10_voll: B16LevelRegister::new(),
            voice10_volr: B16LevelRegister::new(),
            voice10_srate: B16LevelRegister::new(),
            voice10_saddr: B16LevelRegister::new(),
            voice10_adsr: B32LevelRegister::new(),
            voice10_cvol: B16LevelRegister::new(),
            voice10_raddr: B16LevelRegister::new(),
            voice11_voll: B16LevelRegister::new(),
            voice11_volr: B16LevelRegister::new(),
            voice11_srate: B16LevelRegister::new(),
            voice11_saddr: B16LevelRegister::new(),
            voice11_adsr: B32LevelRegister::new(),
            voice11_cvol: B16LevelRegister::new(),
            voice11_raddr: B16LevelRegister::new(),
            voice12_voll: B16LevelRegister::new(),
            voice12_volr: B16LevelRegister::new(),
            voice12_srate: B16LevelRegister::new(),
            voice12_saddr: B16LevelRegister::new(),
            voice12_adsr: B32LevelRegister::new(),
            voice12_cvol: B16LevelRegister::new(),
            voice12_raddr: B16LevelRegister::new(),
            voice13_voll: B16LevelRegister::new(),
            voice13_volr: B16LevelRegister::new(),
            voice13_srate: B16LevelRegister::new(),
            voice13_saddr: B16LevelRegister::new(),
            voice13_adsr: B32LevelRegister::new(),
            voice13_cvol: B16LevelRegister::new(),
            voice13_raddr: B16LevelRegister::new(),
            voice14_voll: B16LevelRegister::new(),
            voice14_volr: B16LevelRegister::new(),
            voice14_srate: B16LevelRegister::new(),
            voice14_saddr: B16LevelRegister::new(),
            voice14_adsr: B32LevelRegister::new(),
            voice14_cvol: B16LevelRegister::new(),
            voice14_raddr: B16LevelRegister::new(),
            voice15_voll: B16LevelRegister::new(),
            voice15_volr: B16LevelRegister::new(),
            voice15_srate: B16LevelRegister::new(),
            voice15_saddr: B16LevelRegister::new(),
            voice15_adsr: B32LevelRegister::new(),
            voice15_cvol: B16LevelRegister::new(),
            voice15_raddr: B16LevelRegister::new(),
            voice16_voll: B16LevelRegister::new(),
            voice16_volr: B16LevelRegister::new(),
            voice16_srate: B16LevelRegister::new(),
            voice16_saddr: B16LevelRegister::new(),
            voice16_adsr: B32LevelRegister::new(),
            voice16_cvol: B16LevelRegister::new(),
            voice16_raddr: B16LevelRegister::new(),
            voice17_voll: B16LevelRegister::new(),
            voice17_volr: B16LevelRegister::new(),
            voice17_srate: B16LevelRegister::new(),
            voice17_saddr: B16LevelRegister::new(),
            voice17_adsr: B32LevelRegister::new(),
            voice17_cvol: B16LevelRegister::new(),
            voice17_raddr: B16LevelRegister::new(),
            voice18_voll: B16LevelRegister::new(),
            voice18_volr: B16LevelRegister::new(),
            voice18_srate: B16LevelRegister::new(),
            voice18_saddr: B16LevelRegister::new(),
            voice18_adsr: B32LevelRegister::new(),
            voice18_cvol: B16LevelRegister::new(),
            voice18_raddr: B16LevelRegister::new(),
            voice19_voll: B16LevelRegister::new(),
            voice19_volr: B16LevelRegister::new(),
            voice19_srate: B16LevelRegister::new(),
            voice19_saddr: B16LevelRegister::new(),
            voice19_adsr: B32LevelRegister::new(),
            voice19_cvol: B16LevelRegister::new(),
            voice19_raddr: B16LevelRegister::new(),
            voice20_voll: B16LevelRegister::new(),
            voice20_volr: B16LevelRegister::new(),
            voice20_srate: B16LevelRegister::new(),
            voice20_saddr: B16LevelRegister::new(),
            voice20_adsr: B32LevelRegister::new(),
            voice20_cvol: B16LevelRegister::new(),
            voice20_raddr: B16LevelRegister::new(),
            voice21_voll: B16LevelRegister::new(),
            voice21_volr: B16LevelRegister::new(),
            voice21_srate: B16LevelRegister::new(),
            voice21_saddr: B16LevelRegister::new(),
            voice21_adsr: B32LevelRegister::new(),
            voice21_cvol: B16LevelRegister::new(),
            voice21_raddr: B16LevelRegister::new(),
            voice22_voll: B16LevelRegister::new(),
            voice22_volr: B16LevelRegister::new(),
            voice22_srate: B16LevelRegister::new(),
            voice22_saddr: B16LevelRegister::new(),
            voice22_adsr: B32LevelRegister::new(),
            voice22_cvol: B16LevelRegister::new(),
            voice22_raddr: B16LevelRegister::new(),
            voice23_voll: B16LevelRegister::new(),
            voice23_volr: B16LevelRegister::new(),
            voice23_srate: B16LevelRegister::new(),
            voice23_saddr: B16LevelRegister::new(),
            voice23_adsr: B32LevelRegister::new(),
            voice23_cvol: B16LevelRegister::new(),
            voice23_raddr: B16LevelRegister::new(),
            data_fifo: Fifo::new(64, Some(DebugState::new("SPU FIFO", false, false))),
            controller_state: Mutex::new(ControllerState::new()),
        }
    }
}
